[package]
name = "libnm"
version = "0.1.0"
edition = "2024"

[dependencies]
gio = "0.21.5"
glib = "0.21.5"
nm-sys = { path = "libnm-sys" }

[features]
v1_2 = []
v1_4 = []
v1_6 = []
v1_8 = []
v1_10 = []
v1_12 = []
v1_14 = []
v1_16 = []
v1_18 = []
v1_20 = []
v1_22 = []
v1_24 = []
v1_26 = []
v1_28 = []
v1_30 = []
v1_32 = []
v1_34 = []
v1_36 = []
v1_38 = []
v1_40 = []
v1_42 = []
v1_44 = []
v1_46 = []
v1_48 = []
v1_50 = []
v1_52 = []
v1_54 = []
gio_v2_22 = []
