[options]
girs_directories = ["gtk-girs", "gir"]
library = "NM"
version = "1.0"
min_cfg_version = "1.0"
target_path = "."
work_mode = "normal"
use_gi_docgen = true
generate_safety_asserts = true
deprecate_by_min_version = true
single_version_file = "."
generate_builder = true
trust_return_value_nullability = true

generate = [
    "NM.80211ApFlags",
    "NM.80211ApSecurityFlags",
    "NM.80211Mode",
    "NM.AccessPoint",
    "NM.Object",
    "NM.ActivationStateFlags",
    "NM.RemoteConnection",
    "NM.Connection",
    "NM.ActiveConnection",
    "NM.Device",
    "NM.DhcpConfig",
    "NM.IPConfig",
    "NM.ActiveConnectionState",
    "NM.ActiveConnectionStateReason",
    "NM.AgentManagerError",
    "NM.BluetoothCapabilities",
    "NM.BridgeVlan",
    "NM.Capability",
    "NM.Checkpoint",
    "NM.CheckpointCreateFlags",
    "NM.Client",
    "NM.SettingsAddConnection2Flags",
    "NM.ConnectivityState",
    "NM.DnsEntry",
    "NM.ClientInstanceFlags",
    "NM.Metered",
    "NM.ClientPermissionResult",
    "NM.ClientPermission",
    "NM.Ternary",
    "NM.RadioFlags",
    "NM.State",
    "NM.ManagerReloadFlags",
    "NM.ClientError",
    "NM.SettingClearSecretsWithFlagsFn",
    "NM.SettingCompareFlags",
    "NM.SettingValueIterFn",
    "NM.Setting8021x",
    "NM.Setting",
    "NM.SettingAdsl",
    "NM.SettingBluetooth",
    "NM.SettingBond",
    "NM.SettingBridge",
    "NM.SettingBridgePort",
    "NM.SettingCdma",
    "NM.SettingConnection",
    "NM.SettingDcb",
    "NM.SettingDummy",
    "NM.SettingGeneric",
    "NM.SettingGsm",
    "NM.SettingInfiniband",
    "NM.SettingIP4Config",
    "NM.SettingIPConfig",
    "NM.SettingIP6Config",
    "NM.SettingIPTunnel",
    "NM.SettingMacsec",
    "NM.SettingMacvlan",
    "NM.SettingOlpcMesh",
    "NM.SettingOvsBridge",
    "NM.SettingOvsPatch",
    "NM.SettingOvsPort",
    "NM.SettingPpp",
    "NM.SettingPppoe",
    "NM.SettingProxy",
    "NM.SettingSerial",
    "NM.SettingTCConfig",
    "NM.SettingTeam",
    "NM.SettingTeamPort",
    "NM.SettingTun",
    "NM.SettingVlan",
    "NM.SettingVpn",
    "NM.SettingVxlan",
    "NM.SettingWimax",
    "NM.SettingWired",
    "NM.SettingWireless",
    "NM.SettingWirelessSecurity",
    "NM.ConnectionSerializationFlags",
    "NM.ConnectionError",
    "NM.ConnectionMultiConnect",
    "NM.CryptoError",
    "NM.DeviceCapabilities",
    "NM.DeviceType",
    "NM.DeviceInterfaceFlags",
    "NM.LldpNeighbor",
    "NM.DeviceState",
    "NM.DeviceStateReason",
    "NM.Device6Lowpan",
    "NM.DeviceAdsl",
    "NM.DeviceBond",
    "NM.DeviceBridge",
    "NM.DeviceBt",
    "NM.DeviceDummy",
    "NM.DeviceError",
    "NM.DeviceGeneric",
    "NM.DeviceHsr",
    "NM.DeviceIPTunnel",
    "NM.IPTunnelFlags",
    "NM.IPTunnelMode",
    "NM.DeviceInfiniband",
    "NM.DeviceIpvlan",
    "NM.DeviceLoopback",
    "NM.DeviceMacsec",
    "NM.DeviceMacvlan",
    "NM.DeviceModem",
    "NM.DeviceModemCapabilities",
    "NM.DeviceOlpcMesh",
    "NM.DeviceWifi",
    "NM.DeviceOvsBridge",
    "NM.DeviceOvsPort",
    "NM.DevicePpp",
    "NM.DeviceReapplyFlags",
    "NM.DeviceTeam",
    "NM.DeviceTun",
    "NM.DeviceVeth",
    "NM.DeviceEthernet",
    "NM.DeviceVlan",
    "NM.DeviceVrf",
    "NM.DeviceVxlan",
    "NM.DeviceWifiCapabilities",
    "NM.DeviceWifiP2P",
    "NM.WifiP2PPeer",
    "NM.WimaxNsp",
    "NM.DeviceWimax",
    "NM.DeviceWireGuard",
    "NM.DeviceWpan",
    "NM.DhcpHostnameFlags",
    "NM.IPAddress",
    "NM.IPAddressCmpFlags",
    "NM.IPRoute",
    "NM.IPRoutingRule",
    "NM.IPRoutingRuleAsStringFlags",
    "NM.KeyfileWarnSeverity",
    "NM.KeyfileHandlerFlags",
    "NM.KeyfileHandlerType",
    "NM.KeyfileReadHandler",
    "NM.KeyfileWriteHandler",
    "NM.ManagerError",
    "NM.MptcpFlags",
    "NM.Range",
    "NM.SettingsConnectionFlags",
    "NM.SettingsUpdate2Flags",
    "NM.RollbackResult",
    "NM.SecretAgentCapabilities",
    "NM.SecretAgentError",
    "NM.SecretAgentGetSecretsFlags",
    "NM.SecretAgentOld",
    "NM.SettingSecretFlags",
    "NM.UtilsPredicateStr",
    "NM.Setting6Lowpan",
    "NM.Setting8021xCKScheme",
    "NM.Setting8021xAuthFlags",
    "NM.Setting8021xCKFormat",
    "NM.SettingBondPort",
    "NM.SettingConnectionAutoconnectSlaves",
    "NM.SettingConnectionDnsOverTls",
    "NM.SettingConnectionDownOnPoweroff",
    "NM.SettingConnectionLldp",
    "NM.SettingConnectionLlmnr",
    "NM.SettingConnectionMdns",
    "NM.SettingDcbFlags",
    "NM.SettingDiffResult",
    "NM.SettingEthtool",
    "NM.SettingEthtoolFecMode",
    "NM.SettingHostname",
    "NM.SettingHsr",
    "NM.SettingIP4DhcpIpv6OnlyPreferred",
    "NM.SettingIP4LinkLocal",
    "NM.SettingIP6ConfigAddrGenMode",
    "NM.SettingIP6ConfigPrivacy",
    "NM.SettingIPConfigForwarding",
    "NM.SettingIPConfigRoutedDns",
    "NM.SettingIpvlanMode",
    "NM.SettingIpvlan",
    "NM.SettingLink",
    "NM.SettingLoopback",
    "NM.SettingMacRandomization",
    "NM.SettingMacsecMode",
    "NM.SettingMacsecOffload",
    "NM.SettingMacsecValidation",
    "NM.SettingMacvlanMode",
    "NM.SettingMatch",
    "NM.SettingOvsDpdk",
    "NM.SettingOvsDpdkLscInterrupt",
    "NM.SettingOvsExternalIDs",
    "NM.SettingOvsOtherConfig",
    "NM.SettingPrefixDelegation",
    "NM.SettingProxyMethod",
    "NM.SettingSerialParity",
    "NM.SettingSriov",
    "NM.SriovVF",
    "NM.SriovEswitchEncapMode",
    "NM.SriovEswitchInlineMode",
    "NM.SriovEswitchMode",
    "NM.SriovPreserveOnDown",
    "NM.TCQdisc",
    "NM.TCTfilter",
    "NM.TeamLinkWatcher",
    "NM.SettingTunMode",
    "NM.SettingUser",
    "NM.SettingVeth",
    "NM.VlanPriorityMap",
    "NM.VlanFlags",
    "NM.SettingVrf",
    "NM.SettingWifiP2P",
    "NM.SettingWirelessSecurityWpsMethod",
    "NM.SettingWireGuard",
    "NM.WireGuardPeer",
    "NM.SettingWiredWakeOnLan",
    "NM.SettingWirelessChannelWidth",
    "NM.SettingWirelessWakeOnWLan",
    "NM.SettingWirelessPowersave",
    "NM.SettingWirelessSecurityFils",
    "NM.SettingWirelessSecurityPmf",
    "NM.WepKeyType",
    "NM.SettingWpan",
    "NM.SettingsError",
    "NM.SimpleConnection",
    "NM.SriovVFVlanProtocol",
    "NM.TCAction",
    "NM.TeamLinkWatcherArpPingFlags",
    "NM.UtilsCheckFilePredicate",
    "NM.UtilsFileSearchInPathsPredicate",
    "NM.UtilsSecurityType",
    "NM.VersionInfoCapability",
    "NM.VpnConnection",
    "NM.VpnConnectionState",
    "NM.VpnConnectionStateReason",
    "NM.VpnEditor",
    "NM.VpnEditorPlugin",
    "NM.VpnEditorPluginCapability",
    "NM.VpnPluginInfo",
    "NM.VpnPluginError",
    "NM.VpnPluginFailure",
    "NM.VpnPluginOld",
    "NM.VpnServiceState",
    "NM.VpnServicePlugin",
    "NM.WimaxNspNetworkType",
]
manual = [
    "Gio.AsyncInitable",
    "Gio.Initable",
    "NM.KeyfileHandlerData",
    "NM.VariantAttributeSpec",
    "NM.VpnEditorPluginVT",
    "GLib.Error",
    "Gio.Cancellable",
]

[[object]]
name = "NM.*"
status = "generate"
